# Use kubectl apply -k . for kustomize deployment
# Or kubectl apply -f . for direct deployment

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml

images:
- name: 320644768930.dkr.ecr.ap-northeast-2.amazonaws.com/charon-test
  newTag: latest

commonLabels:
  app: charon-blog
  version: v1.0.0